### ISSUE TITLE
O_o PHP?

### ISSUE THREAD

**Issue by dmitryTsatsarin** [oscarmlage/django-cruds-adminlte#10]
why?

[https://github.com/oscarmlage/django-cruds-adminlte/blob/e89bda009453fcda8f4c3be6e209bb3830068965/cruds_adminlte/static/ckeditor/samples/old/assets/posteddata.php](https://github.com/oscarmlage/django-cruds-adminlte/blob/e89bda009453fcda8f4c3be6e209bb3830068965/cruds_adminlte/static/ckeditor/samples/old/assets/posteddata.php)

**Comment by oscarmlage** [comment]
Hey @dmitryTsatsarin!

Thanks for your comment, it seems that the code is some kind of php sample included in ckeditor "bundle". I'm going to remove it. Thanks again for the feedback!.
