### ISSUE TITLE
does this support all adminlte components and widgets?

### ISSUE THREAD

**Issue by bytearchive** [oscarmlage/django-cruds-adminlte#112]
i.e how can I use the adminlte widget inside a django template

**Comment by oscarmlage** [comment]
No, `django-cruds-adminlte` does not support all the `AdminLTE` widgets, only a few... but it's prepared to add all of them!.

I mean for now you can see some widgets (datepicket, timepicker, colorpicker, ckeditor...) already written in [widgets.py](https://github.com/oscarmlage/django-cruds-adminlte/blob/master/cruds_adminlte/widgets.py) so feel free to contribute and add the ones you need.

Would be a really awesome PR @bytearchive.
