### ISSUE TITLE
Can the form customize the Name of a field? For example, one of the fields in my model is Name. I want him to call another name, such as: YourName

### ISSUE THREAD

**Issue by WOSHIliuhailong** [oscarmlage/django-cruds-adminlte#113]
Can the form customize the Name of a field? For example, one of the fields in my model is Name. I want him to call another name, such as: YourName

**Comment by WOSHIliuhailong** [comment]
Or is it okay to use other languages?  I didn't find anything about customization in the document.

**Comment by WOSHIliuhailong** [comment]
Well, I found the solution myself. With verbose_name, I am not a qualified programmer.😂

**Comment by oscarmlage** [comment]
In the model definition you can change the [verbose_name](https://docs.djangoproject.com/en/2.2/ref/models/fields/#django.db.models.Field.verbose_name) attribute.
