### ISSUE TITLE
ManyToMany fields 

### ISSUE THREAD

**Issue by kptac** [oscarmlage/django-cruds-adminlte#122]
Looks like ManyToMany fields do not work. Perhaps we can add a linked string representation of each object within columns. 
#123

**Comment by oscarmlage** [comment]
The PR was already merged, Thanks for the contribution @kptac

**Comment by benmaier** [comment]
hey @kptac I'm currently having the problems that ManyToMany-field values are neither shown in the list-view nor in the-display. It seems you have solved this problem with this PR but to me it's unclear how to use this. Would you mind a short explanation?

**Comment by kptac** [comment]
@benmaier - make sure to have a string representation set by implementing Model.__str__() method.

Also, are you on the latest version?

Hope that helps.

**Comment by benmaier** [comment]
My Geoname-model already has this property

> The latest release is: 0.0.17+git.081101d

Yes, I know, but this release is from July 10 and does not include your changes (see e.g. https://github.com/oscarmlage/django-cruds-adminlte/tree/0.0.17%2Bgit.081101d/cruds_adminlte/templates/cruds/columns where your file ). I'm on the latest master commit which is 0.0.17+git.a154def and includes your changes.

**Comment by kptac** [comment]
Ahh ok, my bad, didn't see the commits on the latest release. So in your CRUDView, are you including the m2m field in **list_fields**? Can I see how you're inheriting CRUDView?

**Comment by benmaier** [comment]
Ah! `list_fields` wasn't mentioned anywhere in the documentation, so I didn't know about it. That did the trick, thank you so much!
