### ISSUE TITLE
Extra Acctions

### ISSUE THREAD

**Issue by fjbardelli** [oscarmlage/django-cruds-adminlte#142]
it is possible to add extas actions to (list, create, edit, delete) in the list.

For example Cancel, and change state, associated with a custom url.

**Thank you**

**Comment by oscarmlage** [comment]
Yes it is. If you open `cruds_adminlte/templates/cruds/list.html` [around line 99](https://github.com/oscarmlage/django-cruds-adminlte/blob/master/cruds_adminlte/templates/cruds/list.html#L99), there is a `{% block actions %}` that you can extend in a custom template to put there all the custom actions you want.

**Comment by fjbardelli** [comment]
Thanks
