### ISSUE TITLE
Paginate elements

### ISSUE THREAD

**Issue by oscarmlage** [oscarmlage/django-cruds-adminlte#23]
Pagination is not working, in fact, has to be done.

**Comment by JuniorBee** [comment]
When are you planning to implement this feature. It is very important as no one can expect a list page without paging.

**Comment by oscarmlage** [comment]
TBD:

- Create different kind of pagination links and let the user choose in a config-like style
- Let the user define the number of items to be paginated. For now it's hardcoded to 10 in the code.

**Comment by oscarmlage** [comment]
@JuniorBee Hope it helps, at least in a short term.

**Comment by luisza** [comment]
mmm pagination is supported right now in cruds.py, but not implemented in template, so 
you can use 

> paginate_by 

to include pagination object to template, and implement your own template pagination.

**Comment by oscarmlage** [comment]
I've added a tiny commit - taking advantage of the _paginate_by_ already implemented by @luisza -
 adding a really simple pagination system in template (just to see if it works for @JuniorBee). I would like to work a bit more on this and to have, at least, a couple of different paginators and let the user decide to use one of the other:

- [ prev | next ]
- [ 1 | 2 | 3 * 4 * 5 | 6 | 7 ]

What do you think?, where do you would put the proper setting?.

**Comment by luisza** [comment]
PR #39 support both cases using template pagination, and other ways to make pagination

*    [ prev | next ]  use  cruds/pagination/prev_next.html
*   [ 1 | 2 | 3 * 4 * 5 | 6 | 7 ]  use cruds/pagination/enumeration.html

Also positions support are done (*Bottom*, *Both*, *Up*)

**Comment by oscarmlage** [comment]
I think we can close this ticket, as it's implemented in #39
