### ISSUE TITLE
Implement search

### ISSUE THREAD

**Issue by oscarmlage** [oscarmlage/django-cruds-adminlte#27]
We should research some way to implement a search feature

**Comment by luisza** [comment]
How we want to implement search, with django-selects or simple search field ?
If it's simple search field maybe i can implement something like django admin

**Comment by oscarmlage** [comment]
I'm my head I was thinking of just a simple search field in the frontend (like Django Admin does), and in the "backstage" some place where to config what fields are going to be searchables. What do you think?

**Comment by luisza** [comment]
Mmm something like #28 ?

**Comment by oscarmlage** [comment]
#28 fixes this, thanks @luisza
