### ISSUE TITLE
Filters

### ISSUE THREAD

**Issue by oscarmlage** [oscarmlage/django-cruds-adminlte#29]
Django Admin has filters for the listings, something like:

```python
    list_filter = ('provider', 'date', 'paid', 'registered')
    list_filter = (('date', DateRangeFilter),
                   ('customer', admin.RelatedOnlyFieldListFilter),)
```
is converted in something like:

![image](https://cloud.githubusercontent.com/assets/98542/25915645/6c08cf62-35c2-11e7-87b1-f558ab23b786.png)

I've not thought about how it could be done in a simple way, maybe something similar to widgets:

1. Declare the filter field and type, i.e.: `('date', DateFilter)`,` ('customer', RelatedFilter)` `('status', BoolFilter)`...
2. Define the action for every kind of filter: `date <= request.input`, `customer.pk=request.input`, `status = True/False`...
3. Define how to paint the widget of every filter (date selector, just a link, dropdown select...)

Brainstorming mode is open :)

**Comment by luisza** [comment]
Sound good,
I did something similar in other project for django admin view, maybe this could help
https://github.com/luisza/django-cruds-adminlte/blob/filter/cruds_adminlte/filter.py
mode of use:
```
# do a form ticketForm
class ticketFilter(FormFilter):
    template = "filter_template.html"
    title = "ticket filter title"
    form = ticketForm
    form_instance = None
    remove_params = ['filtro', 'field_text', 'otherautocompletefield_text']
    map_parameters = {'cicle': 'acrrosmodelworks__ciclo',
                      'othermapfield': 'other model field'}
```

I have no time this week to implement it, but as summary with this you can put whatever form you want to filter, also forms than has autocomplete (django-ajaxselect).

One think more it's also important include a preserver filter feature so search and filter could work in the same view.

Other thing.  Django admin filter thieft a lot of space show filter, maybe we can put some vertical colapse to show or hide filter

**Comment by luisza** [comment]
PR #40 help to solve this :), maybe a look revision needed.

**Comment by oscarmlage** [comment]
I'm off for vacations these days but definitely I'm looking forward to have time to review the PR. Thanks for the work @luisza

**Comment by luisza** [comment]
This issue was reviewed ? If not maybe the filter functionality solve this issue and could be close

**Comment by oscarmlage** [comment]
4538715 Adds the filters as feature. Thanks @luisza for the effort.
