### ISSUE TITLE
Implement Auth and CRUD for users, groups and permissions

### ISSUE THREAD

**Issue by oscarmlage** [oscarmlage/django-cruds-adminlte#4]
Would be nice to have some kind of auth for the cruds. And would be even prettier to be able to CRUD users, groups and permissions like the django built-in admin does.

**Comment by luisza** [comment]
I am working in something similar that could be usefull 

https://github.com/luisza/djreservation/blob/master/djreservation/contrib/CRUD.py

**Comment by luisza** [comment]
Hi, I make a PR #9 thats implements this feature

**Comment by oscarmlage** [comment]
Commit 70fe2c1d7a956b39aa7734025d58fc945d48aebb fixes this, thanks to @luisza.
