### ISSUE TITLE
Is package ready to use in Django 2.0?

### ISSUE THREAD

**Issue by koddr** [oscarmlage/django-cruds-adminlte#43]
Hello. 

Small question about your admin package: is package ready to use in Django 2.0?

Thanks.

**Comment by oscarmlage** [comment]
No it isn't. I didn't tried it in Django 2.0 yet, but feel free to give it a try. Reports are welcomed! (and PRs too) ;-)

**Comment by luisza** [comment]
Hi, 

I hope to have time this weekend to update to Django 2.0, but also we need unitest to support multiples django version, so help is welcome.

**Comment by luisza** [comment]
Hi, #47  fixes some incompatibilities on django 2.0 so now we support django 1.10, 1.11 and 2.0
