### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by fjbardelli** [oscarmlage/django-cruds-adminlte#44]
It is possible to translate button and title labels into other languages

**Comment by luisza** [comment]
Hi,
Inside the code we use translation approach so it's possible to make translation with only the django commands like

>  python manage.py makemessages  -l es

translate to your language and compile

> python manage.py compilemessages -l es

If you want to make a PR  with you translation is always welcome.

**Comment by fjbardelli** [comment]
Thanks
