### ISSUE TITLE
Sidebar models not loading

### ISSUE THREAD

**Issue by tanasecucliciu** [oscarmlage/django-cruds-adminlte#45]
Hello,

Let me preface this by saying that I'm relatively new to web development & Django. I'm not sure but I presume the menu sidebar should generate buttons for all my models. I think this behaviour should just work out of the box after installation based on this bit of code from the default sidebar.html:

```
{% for model in models %}
                <li>
                    <a href="{% url model.url %}">
                        <i class="fa fa-dashboard"></i> <span>{{ model.plural }}</span>
                    </a>
                </li>
{% endfor %}
```

Needless to say, it doesn't do anything and for the life of me, I can't seem to figure out why.

My project follows [this](https://github.com/pydanny/cookiecutter-django) template.

If you guys can point me in the right direction I would really appreciate it.

Thank you!

**Comment by oscarmlage** [comment]
@tanasecucliciu you need to pass your app/project through our urls functions (`crud_for_model` or `crud_for_app`) in your urls.py, i.e.:

```python
urlpatterns+= crud_for_app('testapp', check_perms=True)
```
Take a look to the `demo/testapp` code in the repo and [the docs](http://django-cruds-adminlte.readthedocs.io/en/latest/installation.html#quickstart). Hope it helps.
