### ISSUE TITLE
Installation bug

### ISSUE THREAD

**Issue by sa9** [oscarmlage/django-cruds-adminlte#5]
Neat package! Thank you!

I'll try to help with bugs reporting and fixes.  Here is my first batch. During installation with ```git clone``` I got the following:

1) missing ```HISTORY.rst'``` file.

https://github.com/oscarmlage/django-cruds/blob/master/setup.py#L24

2) The ```django-cruds``` requires ```django-compressor``` package:

https://github.com/oscarmlage/django-cruds/blob/master/cruds/templates/cruds/base.html#L5

I guess this need to be added to the installation docs. 

3) Using ```pip install django-cruds``` installs a different repo at https://github.com/bmihelac/django-cruds

Is there a way to change the name of this package to ```django-cruds2``` for example?

**Comment by oscarmlage** [comment]
Hey @sa9, welcome!

First of all thank you for the comment and for your time. You're totally right in all the spots. I'm working on it right now.

1. Agree, fixing
2. Not needed really, I'll remove the compress templatetag.
3. I've renamed the repo, the new one is django-cruds-adminlte. I'm going to publish the package in pypi too to make the installation more easy (and write something related to this in the docs).

Thank you :)
