### ISSUE TITLE
ULRs

### ISSUE THREAD

**Issue by fjbardelli** [oscarmlage/django-cruds-adminlte#51]
it is possible to generate a url for a model, for example to list the docoments of a client, or to create more views, part of creating, listing, deleting, etc. as for example approve_

Thank you

**Comment by oscarmlage** [comment]
Sure, you can add your own routes or, even better, extend the ones from the crud and do your own logic and templates. Perhaps the documentation may help you:

- http://django-cruds-adminlte.readthedocs.io/en/latest/installation.html#urls-for-the-crud
- http://django-cruds-adminlte.readthedocs.io/en/latest/installation.html#cruds-for-app

Hope it helps.
