### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by luisza** [oscarmlage/django-cruds-adminlte#53]
Hi, It's possible to make a new release of this software.

- There is 2 pull request than have impact in the software (django 2.0 support) and bux fixed in filter.
- Actual package is break in python 3 (but master is ok).

So I think new release is important.

**Comment by oscarmlage** [comment]
Sure, I'll pack the new release.

**Comment by oscarmlage** [comment]
Release done, _0.0.9_ is out there.

Thanks guys for all the code, help and support :)
