### ISSUE TITLE
displays link to image instead of the actually image itself.

### ISSUE THREAD

**Issue by igabice** [oscarmlage/django-cruds-adminlte#54]
hello,
thanks for this wonderful app, it saved me a lot time.
I have a model with an imageField, i would like to display the actual image but instead i get the name of the image in both the list and detail view and only when the name is clicked can i see the image. please how can i make the image display in both list and detail view?

**Comment by luisza** [comment]
Hi, I am not sure if this work, but you can overwrite de get_FOO_display
 https://docs.djangoproject.com/en/2.0/ref/models/instances/#django.db.models.Model.get_FOO_display

django-cruds-adminlte first check if get_FOO_display if found call this function.

**Comment by oscarmlage** [comment]
Hmm, for the list you can just extend the ''templates/cruds/columns/filefield.html'' or change a bit the 
 code (PR is welcome!) and create a custom field for the images (something like imagefield would be really nice).

For the detail view we're using the html from ''django-image-cropping'' (https://github.com/jonasundderwolf/django-image-cropping) so, I think the right way is to look for how to extend it in the docs of the project.

Please keep me updated with the progress.

**Comment by igabice** [comment]
i added the code below in the filefield.html located at cruds_adminlte/templates/cruds/columns/filefield.html the image now displays in list view but i only get the link when in detail view.

`<img src="{{ object.image.url }}"  alt="image" style="width:400px; max-height:600px" />`
