### ISSUE TITLE
Limit model instances available to CRUD View

### ISSUE THREAD

**Issue by fjbardelli** [oscarmlage/django-cruds-adminlte#55]
It is possible to work with a model, but not with all the data. For example, define the view as follows

class vExamen2 (CRUDView):
     model = Exam.objects.filter (id = 1)

**Comment by luisza** [comment]
No, is it. 

model is a class not instance or queryset. Because there are no sense have list view, add view if you have only one instance.

See 
http://django-cruds-adminlte.readthedocs.io/en/latest/usage.html#overwrite-views

**Comment by oscarmlage** [comment]
@fjbardelli was it helpful? Please give us some feedback to keep the issue open or close it. Thanks.

**Comment by telenieko** [comment]
As far as I understand the original comment, the request is for what already exists in Django views (queryset). Anyway, closing due to lack of folloup by the submitter.
