### ISSUE TITLE
error when add new costumer

### ISSUE THREAD

**Issue by Jen-Persly** [oscarmlage/django-cruds-adminlte#60]
I found error when I try to add (create) new costumer
this the error message

> IntegrityError at /lte/testapp/customer/create
(1048, "Column 'time' cannot be null")

<img width="914" alt="screen shot 2018-02-23 at 16 05 15" src="https://user-images.githubusercontent.com/11174736/36586355-0715030c-18b4-11e8-916c-300455f14155.png">

**Comment by migue56** [comment]
Hi Jen-Presley.
Well, compare the **crud view fields** with the **models fields**. To use all your models fields on the createview.
You need to set on the view of "Customer"    
`fields = '__all__'` 
or   comment  it  `#fields = '__all__'`  to cruds-adminlte  set the default `__all__`
```

class CustomerCRUD(CRUDView):
#fields = [ #list of fields]  # default all with '__all__'
```
