### ISSUE TITLE
Link

### ISSUE THREAD

**Issue by fjbardelli** [oscarmlage/django-cruds-adminlte#61]
in the lists, the fields of a foreign key, are shown as a link to an update form, it is possible that those links will not die or do so with a detail form.
Thank you

**Comment by oscarmlage** [comment]
I'm going to close this issue as **duped**, we will follow the thread in the issue #71, already answered there an user with  a question quite similar to this one. Please let me know if it worked for you. Otherwise please add your feedback there or reopen. Sorry for the inconvenience.
