### ISSUE TITLE
create and update view for selected users

### ISSUE THREAD

**Issue by igabice** [oscarmlage/django-cruds-adminlte#62]
hello, 
how can i make create and update view available for specific users only? I really don't understand how adding permission to a model's metadata works.

**Comment by oscarmlage** [comment]
@igabice I guess it would be nice for the community (_and the upcoming users_)  if you add a little comment about how do you manage to resolve this. Thanks in advance.

**Comment by igabice** [comment]
to solve this i wrapped the edit button in list.html file with an if statement that checks if the current user is staff(i.e request.user.is_staff)  before making the button visible. so only users who belong to the staff group can see the edit button .
