### ISSUE TITLE
Django 2.0.2

### ISSUE THREAD

**Issue by fjbardelli** [oscarmlage/django-cruds-adminlte#63]
Version 0.0.9 is not compatible with Django 2.0.2?
What is the correct version to work with Django 2.0.2.

Thanks

**Comment by luisza** [comment]
Why you say that 0.0.9 is not compatible with django 2.0.2?  Did you find a bug?

**Comment by fjbardelli** [comment]
if installed with "pip install django-cruds-adminlte", pip list says that version 0.0.9 is installed and I get the following error

NameError at / login /
name 'register_tag' is not defined
Request Method: GET
Request URL: http://127.0.0.1:8001/login/
Django Version: 2.0.2
Exception Type: NameError
Exception Value:
name 'register_tag' is not defined
Exception Location: /home/fernando/.virtualenvs/secdj2/lib/python3.5/site-packages/cruds_adminlte/templatetags/crud_tags.py in <module>, line 31
Python Executable: /home/fernando/.virtualenvs/secdj2/bin/python
Python Version: 3.5.2
Python Path:
['/ home / fernando / Sistemas / WebApps / secColegioDJ2',
 '/home/fernando/.virtualenvs/secdj2/lib/python35.zip',
 '/home/fernando/.virtualenvs/secdj2/lib/python3.5',
 '/home/fernando/.virtualenvs/secdj2/lib/python3.5/plat-x86_64-linux-gnu',
 '/home/fernando/.virtualenvs/secdj2/lib/python3.5/lib-dynload',
 '/usr/lib/python3.5',
 '/usr/lib/python3.5/plat-x86_64-linux-gnu',
 '/home/fernando/.virtualenvs/secdj2/lib/python3.5/site-packages']
Server time: Mar, 6 Mar 2018 12:14:15 +0000

if I install it with "pip install e git + https: // github.com/oscarmlage/django-cruds-adminlte.git", pip list, it says that version 0.0.8 is installed, but it's ok.

**Comment by luisza** [comment]
@oscarmlage could you upload a new repared release ?

**Comment by oscarmlage** [comment]
Release done, last version is now `0.0.11`.
