### ISSUE TITLE
Remove django-image-cropping as dependency

### ISSUE THREAD

**Issue by luisza** [oscarmlage/django-cruds-adminlte#80]
Hi,  I am testing this app with django 2.0 but django-image-cropping don't support django 2.x and also have dependency crashes with django-crispy-forms.   
I saw that  django-image-cropping has pull request to support django 2.0 and solve the dependency issues in main branch, but not in pip.
I am checking and cropping image it's not a fundamental feature that we can write something about how to integrate  django-image-cropping and include other requirement.txt file with  others apps than work with this app but are not part of core functionality .

I am working in PR of this and some other little changes that can improve the behavior of this app.

**Comment by luisza** [comment]
See #81

**Comment by oscarmlage** [comment]
PR merged, @luisza thanks for the work!
