### ISSUE TITLE
List View fields order

### ISSUE THREAD

**Issue by kptac** [oscarmlage/django-cruds-adminlte#82]
In list view, I want to show certain fields in a different order. 

class ClientView(CRUDView):
    model = Client
    list_fields = ['id', 'client_name', 'country']

But in list page I get 
Country - Client Name - ID

Why is that?

Using v0.0.13
Django 1.11.11
Python 2.7

**Comment by luisza** [comment]
@oscarmlage  could you please close this Issue, solution was merge days ago.

**Comment by oscarmlage** [comment]
Sure, thanks both!
