### ISSUE TITLE
TimePickerWidget 24 hour time format not working

### ISSUE THREAD

**Issue by bgunebakan** [oscarmlage/django-cruds-adminlte#86]
Hi I am triying to use 24hour format but i cannot handle it.My timefield shows as AM/PM format and i cannot change time.

forms.py
---------------------
'auction_time': TimePickerWidget(
                attrs={'format': 'HH:ii',
                       'icon': 'fa-clock-o'}),

models.py
---------------------
auction_time = models.TimeField(verbose_name='Auction Time', editable=True,null=True, blank=True)

settings.py
---------------------
TIME_INPUT_FORMATS = ('%H:%M','%I:%M %p')

**Comment by bgunebakan** [comment]
timepicker.html
```
<script>
$(function () {
    $(".timepickerwidget").timepicker({
          showInputs: false,
          use24hours: true,
          showMeridian: false   });
});
</script>
```
settings.py
```
TIME_INPUT_FORMATS = ('%H:%M',)
TIME_FORMAT = ('H:i')
```
problem solved.

**Comment by luisza** [comment]
See  https://github.com/oscarmlage/django-cruds-adminlte/blob/master/demo/demo/settings.py
Some useful settings variables. 

TIME_FORMAT = 'h:i A'
DATETIME_FORMAT = 'm/d/Y H:i:s'
DATE_FORMAT = "m/d/Y"
TIME_INPUT_FORMATS = ['%I:%M %p']
