### ISSUE TITLE
Can't save M2M Models

### ISSUE THREAD

**Issue by xyu3xx** [oscarmlage/django-cruds-adminlte#88]
When i add the related_fields in my class (CRUDView) (Like: class CRIView(CRUDView)), my m2m models dont save.
I have resolved this issue adding form.save_m2m() in two places...

def get_create_view(self):
        CreateViewClass = super(CRIView, self).get_create_view()
        class MyListView(CreateViewClass):
            def form_valid(self, form):
                ...
                form.save_m2m()
                 return HttpResponseRedirect(self.get_success_url())

AND in

def get_update_view(self):
        UpdateViewClass = super(CRIView, self).get_update_view()
        class MyListView(UpdateViewClass):
            ...
            def form_valid(self, form):
                ...
                self.object.save()
                form.save_m2m()
                return HttpResponseRedirect(self.get_success_url())

Also created a file called manytomany.html in fileds folder

Thanks!

**Comment by oscarmlage** [comment]
Fixed: d00b5e8430bb9031e084d04f639f7bee1eb614c1
