### ISSUE TITLE
how to integrate in local system face some issues , give proper instruction for install 

### ISSUE THREAD

**Issue by karthiRam96** [oscarmlage/django-cruds-adminlte#94]
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
..E
======================================================================
ERROR: test_add_crud_template (tests.test_views.CRUDMixinTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\webapps\cgassess\tests\test_views.py", line 20, in test_add_crud_template
    view = crud_views.CRUDListView.as_view(model=Author)(request)
AttributeError: module 'cruds_adminlte.views' has no attribute 'CRUDListView'

----------------------------------------------------------------------
Ran 3 tests in 0.203s

FAILED (errors=1)
Destroying test database for alias 'default'...

**Comment by oscarmlage** [comment]
Thanks for the issue @karthiRam96, could you add some more information to the ticket to be able to reproduce the error and look for a fix? (thanks in advance).

**Comment by telenieko** [comment]
This looks very much like the error I found when committing [6c61ec8], so if #104 gets merged this will be fixed. Otherwise that commit can be cherry-picked.

**Comment by telenieko** [comment]
This should be fixed via #104. Lacking any followup from te original reporter I am closing this issue.
